apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-api
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: device-api

  template:
    metadata:
      labels:
        app: device-api

    spec:
      containers:
        - name: device-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9000

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 5

          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 10
