version: "3.8"

services:

  device-api:
    build: ./services/device-api
    ports:
      - "9000:9000"

  telemetry-ingestor:
    build: ./services/telemetry-ingestor
    ports:
      - "8081:8080"

  ota-controller:
    build: ./services/ota-controller
    ports:
      - "7070:7070"

  mqtt-broker:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"

